---
- name: "Execute Terramorph destroy -force in {{ directory }}"
  command: "/usr/bin/python /app/src/terramorph/terramorph.py {{ directory }} destroy -force"
  delegate_to: 127.0.0.1
  run_once: true